"""Tests for mautrix-style config + registration generation."""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from reelgrab import __app_name__
from reelgrab.config import (
    bootstrap,
    build_registration,
    parse_config_dict,
    write_default_config,
)


class TestBootstrap(unittest.TestCase):
    def test_app_name(self) -> None:
        self.assertEqual(__app_name__, "reelgrab")

    def test_write_default_config_has_sections(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "config.yaml"
            write_default_config(path)
            text = path.read_text()
            self.assertIn("homeserver:", text)
            self.assertIn("appservice:", text)
            self.assertIn("id: reelgrab", text)
            self.assertIn("username: reelgrab", text)
            self.assertIn("example.com", text)
            self.assertNotIn("instamatrix", text)

    def test_first_run_creates_config_and_exits(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            result = bootstrap(data_dir=td)
            self.assertTrue(result.created_config)
            self.assertTrue(result.exit_after)
            self.assertTrue((Path(td) / "config.yaml").is_file())

    def test_second_run_mints_tokens_and_registration(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            d = Path(td)
            write_default_config(d / "config.yaml")
            text = (d / "config.yaml").read_text()
            text = text.replace("domain: example.com", "domain: myserver.test")
            text = text.replace(
                "address: http://localhost:8008",
                "address: http://synapse:8008",
            )
            (d / "config.yaml").write_text(text)

            result = bootstrap(data_dir=td)
            self.assertTrue(result.updated_tokens)
            self.assertTrue(result.created_registration)
            self.assertFalse(result.exit_after)
            reg = (d / "registration.yaml").read_text()
            self.assertIn("as_token:", reg)
            self.assertIn("reelgrab", reg)
            self.assertIn("myserver\\.test", reg)
            self.assertIn("Generated by reelgrab", reg)
            # mautrix-style: registration url points at the appservice listener
            self.assertIn("url:", reg)
            self.assertNotIn("url: null", reg)
            self.assertIn("http://reelgrab:29399", reg)

            cfg_text = (d / "config.yaml").read_text()
            self.assertNotIn("as_token: generate", cfg_text)

    def test_registration_regex(self) -> None:
        cfg = parse_config_dict(
            {
                "homeserver": {"address": "http://hs:8008", "domain": "example.org"},
                "appservice": {
                    "id": "reelgrab",
                    "bot": {"username": "reelgrab"},
                    "as_token": "a" * 32,
                    "hs_token": "b" * 32,
                },
            }
        )
        reg = build_registration(cfg)
        self.assertEqual(reg["sender_localpart"], "reelgrab")
        self.assertEqual(reg["id"], "reelgrab")
        self.assertEqual(reg["url"], "http://reelgrab:29399")
        self.assertEqual(reg["namespaces"]["users"][0]["exclusive"], True)
        self.assertIn("example\\.org", reg["namespaces"]["users"][0]["regex"])
        self.assertEqual(cfg.user_id, "@reelgrab:example.org")

    def test_registration_url_from_appservice_address(self) -> None:
        cfg = parse_config_dict(
            {
                "homeserver": {"domain": "matrix.example"},
                "appservice": {
                    "as_token": "a" * 32,
                    "hs_token": "b" * 32,
                    "address": "http://reelgrab:29399",
                },
            }
        )
        reg = build_registration(cfg)
        self.assertEqual(reg["url"], "http://reelgrab:29399")
        self.assertIn("matrix\\.example", reg["namespaces"]["users"][0]["regex"])

    def test_default_config_includes_avatar(self) -> None:
        with tempfile.TemporaryDirectory() as td:
            path = Path(td) / "config.yaml"
            write_default_config(path)
            text = path.read_text()
            self.assertIn("avatar: default", text)
            self.assertIn('displayname: "🎞️ Reelgrab"', text)

    def test_avatar_path_default_resolves_to_packaged_icon(self) -> None:
        cfg = parse_config_dict({})
        path = cfg.avatar_path()
        self.assertIsNotNone(path)
        assert path is not None
        self.assertTrue(path.is_file(), f"missing packaged icon: {path}")
        self.assertEqual(path.name, "icon.jpg")

    def test_avatar_path_empty_skips(self) -> None:
        cfg = parse_config_dict({"appservice": {"bot": {"avatar": ""}}})
        self.assertIsNone(cfg.avatar_path())

    def test_avatar_path_custom_relative_to_data_dir(self) -> None:
        cfg = parse_config_dict({"appservice": {"bot": {"avatar": "my-avatar.png"}}})
        cfg.data_dir = Path("/tmp/reelgrab-data")
        self.assertEqual(cfg.avatar_path(), Path("/tmp/reelgrab-data/my-avatar.png").resolve())

    def test_avatar_path_absolute(self) -> None:
        cfg = parse_config_dict(
            {"appservice": {"bot": {"avatar": "/opt/icons/bot.png"}}}
        )
        self.assertEqual(cfg.avatar_path(), Path("/opt/icons/bot.png"))


if __name__ == "__main__":
    unittest.main()
